apiVersion: v1
kind: Secret
metadata:
  name: {{ include "afd.fullname" . }}
  labels:
    {{- include "afd.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $token := .Values.authToken | default (randAlphaNum 32) }}
  auth-token: {{ $token | b64enc | quote }}
