run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - govet          # go vet
    - ineffassign    # unused assignments
    - typecheck      # type errors
    - gofmt          # gofmt 格式检查
    - goimports      # import 顺序与分组检查

linters-settings: {}

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
